main: AGTHARN\uhc\Main
name: UHC
author: AGTHARN
version: 1 # based off build number
api: 3.20.1

permissions:
  uhc.vpn.bypass:
    default: op
    description: VPN Checks would not be run on players with this permission
  uhc.mod.command:
    default: op
    description: VPN Checks would not be run on players with this permission