name: UHC
main: AGTHARN\uhc\Main
author: ThePMDuo
authors: [AGTHARN, CosmicNebula200]
version: 1.0.0
api: 4.0.0
extensions:
  Core: '>=8.0'

permissions:
  uhc.vpn.bypass:
    default: false
    description: VPN Checks would not be run on players with this permission
  uhc.mod.command:
    default: false
    description: VPN Checks would not be run on players with this permission