on: [workflow_dispatch]

name: PHPStan

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    
    steps:
        - name: "Checkout"
          uses: actions/checkout@v2
        - name: phpstan
          uses: nxtlvlsoftware/pmmp-phpstan-action@stable
          with:
            phpstan-config: phpstan.neon.dist
