on: [workflow_dispatch]

name: PHPStan

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    
    steps:
        - name: "Checkout"
          uses: actions/checkout@v2

        - name: Run PHPStan
          uses: larryTheCoder/pmmp-phpstan-action@master
          with:
            phpstan-config: phpstan.neon.dist