on:
  workflow_dispatch:
    inputs:
      source:
        description: "Path to the source directory to run analysis on."
        required: false
      phpstan-config:
        description: "Path to the phpstan.neon configuration file."
        required: false
        default: "/pocketmine/phpstan.neon"

name: PHPStan

jobs:
  phpstan:
    name: PHPStan
    
    runs-on: ubuntu-latest
    
    steps:
        - name: "Checkout"
          uses: actions/checkout@v2

        - name: PHPStan
          uses: "docker://nxtlvlsoftware/pmmp-phpstan:master"
          env:
            phpstan-config: ${{ inputs.phpstan-config }}
          with:
            args:
              - ${{ inputs.source }}