on: push

name: CI

jobs:
  phpstan:
    name: PHPStan Checks
    runs-on: ubuntu-latest
    
    steps:
        - name: "Checkout"
          uses: actions/checkout@v2
        - name: phpstan
          uses: nxtlvlsoftware/pmmp-phpstan-action@stable
          with:
            phpstan-config: phpstan.neon.dist
  
  codestyle:
    name: Code Style Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: 7.4
          tools: php-cs-fixer
      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --diff-format=udiff
